name: setup-macos-latest
description: Setup runner (macos)

inputs:
  is-builder:
    description: 'Installs required build tools'
    required: true
  repo-token:
    description: 'The GITHUB_TOKEN secret'
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        echo "Nothing to do"
