name: Log success / failure of a task
description: Log success / failure of a task in the summary of the step

inputs:
  success:
    description: 'Decides if task was successful or not'
    required: false
    default: 'true'
  success_message:
    description: 'Message to be logged if task was successful'
    required: true
  failure_message:
    description: 'Message to be logged if task failed'
    required: false

runs:
  using: "composite"

  steps:
    - if: inputs.success == 'true'
      shell: bash
      run: echo "- [x] ${{ inputs.success_message }}" >> $GITHUB_STEP_SUMMARY
    - if: inputs.success == 'false' && inputs.failure_message != ''
      shell: bash
      run: echo "- [ ] ${{ inputs.failure_message }}" >> $GITHUB_STEP_SUMMARY