name: setup
description: Setup runner

inputs:
  modify_cache:
    description: 'Decides if cache should be modified or restored only'
    required: false
    default: 'false'
  rust:
    description: 'Rust version'
    required: false
    default: 'stable'
  os:
    description: 'Operating system'
    required: false
    default: 'ubuntu-latest'
  github_token:
    description: 'GitHub token'
    required: true

runs:
  using: "composite"

  steps:
    # Do setups that are only required for a specific OS
    - run: echo "## Setup ${{ inputs.os }}" >> $GITHUB_STEP_SUMMARY
      shell: bash
    - name: Setup ubuntu-latest
      if: inputs.os == 'ubuntu-latest'
      uses: ./.github/actions/setup/ubuntu-latest
    - name: Setup windows-latest
      if: inputs.os == 'windows-latest'
      uses: ./.github/actions/setup/windows-latest
    - name: Setup macos-latest
      if: inputs.os == 'macos-latest'
      uses: ./.github/actions/setup/macos-latest

    # Setup tools like rust, protoc, etc.
    - run: echo "## Setup tools" >> $GITHUB_STEP_SUMMARY
      shell: bash
    - name: Setup tools
      uses: ./.github/actions/tools
      with:
        modify_cache: ${{ inputs.modify_cache }}
        rust: ${{ inputs.rust }}
        github_token: ${{ inputs.github_token }}