name: setup
description: Setup runner

inputs:
  repo-token:
    description: 'The GITHUB_TOKEN secret'
    required: true
  os:
    description: 'The OS to setup'
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup ${{ matrix.os }}
      uses: ./.github/actions/setup-${{ github.event.inputs.os }}
    - name: Install protoc
      uses: arduino/setup-protoc@v1
      with:
        repo-token: ${{ inputs.repo-token }}
    - name: Install rust ${{ matrix.rust }}
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        profile: minimal
        override: true
    - name: Setup rust cache
      uses: Swatinem/rust-cache@v2.2.1
      with:
        shared-key: ${{ runner.os }}-${{ matrix.rust }}-${{ hashFiles('**/Cargo.lock') }}
