name: setup
description: Setup runner

inputs:
  repo-token:
    description: 'The GITHUB_TOKEN secret'
    required: true
  is-builder:
    description: 'Installs required build tools and updates cache'
    required: false
    default: 'false'
  rust:
    description: 'Rust version'
    required: false
    default: 'stable'
  os:
    description: 'Operating system'
    required: false
    default: 'ubuntu-latest'

runs:
  using: "composite"

  steps:
    - name: Setup Cache
      if: inputs.is-builder == 'true'
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ inputs.os }}-rust-${{ inputs.rust }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ inputs.os }}-rust-${{ inputs.rust }}-

    - name: Restore cache
      if: inputs.is-builder == 'false'
      uses: actions/cache/restore@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ inputs.os }}-rust-${{ inputs.rust }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ inputs.os }}-rust-${{ inputs.rust }}-

    - name: Install protoc
      if: inputs.is-builder == 'true'
      uses: arduino/setup-protoc@v1
      with:
        repo-token: ${{ inputs.repo-token }}

    - name: Install rust ${{ inputs.rust }}
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ inputs.rust }}
        components: rustfmt, clippy

    - name: Setup ubuntu-latest
      if: inputs.os == 'ubuntu-latest'
      uses: ./.github/actions/setup-ubuntu-latest
      with:
        repo-token: ${{ inputs.repo-token }}
        is-builder: ${{ inputs.is-builder }}
    - name: Setup windows-latest
      if: inputs.os == 'windows-latest'
      uses: ./.github/actions/setup-windows-latest
      with:
        repo-token: ${{ inputs.repo-token }}
        is-builder: ${{ inputs.is-builder }}
    - name: Setup macos-latest
      if: inputs.os == 'macos-latest'
      uses: ./.github/actions/setup-macos-latest
      with:
        repo-token: ${{ inputs.repo-token }}
        is-builder: ${{ inputs.is-builder }}
