name: setup
description: Setup runner

inputs:
  github-token:
    description: 'GitHub token'
    required: true
  create-cache:
    description: 'Creates the cache in case it does not exist'
    required: false
    default: 'false'
  os:
    description: 'Operating system'
    required: false
    default: 'ubuntu-latest'

runs:
  using: "composite"

  steps:
    # Do setups that are only required for a specific OS
    - name: Setup ubuntu-latest
      if: inputs.os == 'ubuntu-latest'
      uses: ./.github/actions/setup/ubuntu-latest
    - name: Setup windows-latest
      if: inputs.os == 'windows-latest'
      uses: ./.github/actions/setup/windows-latest
    - name: Setup macos-latest
      if: inputs.os == 'macos-latest'
      uses: ./.github/actions/setup/macos-latest

    # Setup tools like rust, protoc, etc.
    - name: Setup tools
      uses: ./.github/actions/tools
      with:
        create-cache: ${{ inputs.create-cache }}
        github-token: ${{ inputs.github-token }}