name: setup
description: Setup runner

inputs:
  repo-token:
    description: 'The GITHUB_TOKEN secret'
    required: true
  restore-only:
    description: 'Only restore cache'
    required: false
    default: 'true'
  rust:
    description: 'Rust version'
    required: false
    default: 'stable'
  os:
    description: 'Operating system'
    required: false
    default: 'ubuntu-latest'

runs:
  using: "composite"

  steps:
    - name: Setup Cache
#      if: inputs.restore-only == 'false'
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ inputs.os }}-cargo-${{ inputs.rust }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ inputs.os }}-cargo-${{ inputs.rust }}-

#    - name: Restore cache
#      if: inputs.restore-only == 'true'
#      uses: actions/cache/restore@v3
#      with:
#        path: |
#          ~/.cargo/bin/
#          ~/.cargo/registry/index/
#          ~/.cargo/registry/cache/
#          ~/.cargo/git/db/
#          target/
#        key: ${{ inputs.os }}-cargo-${{ inputs.rust }}-${{ hashFiles('**/Cargo.lock') }}
#        restore-keys: |
#          ${{ inputs.os }}-cargo-${{ inputs.rust }}-

    - name: Install protoc
      uses: arduino/setup-protoc@v1
      with:
        repo-token: ${{ inputs.repo-token }}

    - name: Install rust ${{ inputs.rust }}
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ inputs.rust }}
        copmponents: rustfmt, clippy

    - name: Setup ubuntu-latest
      if: inputs.os == 'ubuntu-latest'
      uses: ./.github/actions/setup-ubuntu-latest
    - name: Setup windows-latest
      if: inputs.os == 'windows-latest'
      uses: ./.github/actions/setup-windows-latest
    - name: Setup macos-latest
      if: inputs.os == 'macos-latest'
      uses: ./.github/actions/setup-macos-latest
