name: setup
description: Setup runner

runs:
  using: "composite"
  steps:
    - name: Test Ubuntu
      if: matrix.os == 'ubuntu-latest'
      shell: bash
      run: echo "ubuntu detected!"
    - name: Install dependencies (linux)
      if: runner.os == 'Linux'
      uses: ./.github/actions/setup-linux
    - name: Install dependencies (windows)
      shell: bash
      run: |
        echo "installing windows deps"
    - name: Install dependencies (macos)
      shell: bash
      run: |
        echo "installing macos deps"
