name: setup
description: Setup runner

inputs:
  repo-token:
    description: 'The GITHUB_TOKEN secret'
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup ubuntu-latest
      if: matrix.os == 'ubuntu-latest'
      uses: ./.github/actions/setup-ubuntu-latest
    - name: Setup windows-latest
      if: matrix.os == 'windows-latest'
      uses: ./.github/actions/setup-windows-latest
    - name: Setup macos-latest
      if: matrix.os == 'macos-latest'
      uses: ./.github/actions/setup-macos-latest

    - name: Setup Cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ matrix.os }}-cargo-${{ matrix.rust }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ matrix.os }}-cargo-${{ matrix.rust }}-

    - name: Install protoc
      uses: arduino/setup-protoc@v1
      with:
        repo-token: ${{ inputs.repo-token }}

    - name: Install rust ${{ matrix.rust }}
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        profile: minimal
        override: true
