name: rust
description: Setup rust

inputs:
  rust:
    description: 'Rust toolchain'
    required: true
  modify_cache:
    description: 'Installs required build tools and updates cache'
    required: true

runs:
  using: "composite"

  steps:
    # Setup cache
    - name: Setup rust cache
      uses: ./.github/actions/util/cache
      with:
        path: |
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: rust-${{ runner.os }}-${{ inputs.rust }}-${{ hashFiles('**/Cargo.lock') }}
        restore_keys: |
          ${{ runner.os }}-rust-${{ inputs.rust }}-
        modify_cache: ${{ inputs.modify_cache }}

    # Install rust
    - name: Install rust ${{ inputs.rust }}
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ inputs.rust }}
        components: rustfmt, clippy