name: tools
description: Install tools

inputs:
  github-token:
    description: 'GitHub token'
    required: true
  create-cache:
    description: 'Creates the cache in case it does not exist'
    required: false
    default: 'false'

runs:
  using: "composite"

  steps:
    # Ensure ~/.local exists
    - run: mkdir -p ~/.local
      shell: bash

    # Install rust
    - uses: ./.github/actions/tools/rust
      with:
        github-token: ${{ inputs.github-token }}
        create-cache: ${{ inputs.create-cache }}

    # Install protoc
    - uses: ./.github/actions/tools/protoc
      with:
        github-token: ${{ inputs.github-token }}
        create-cache: ${{ inputs.create-cache }}