name: tools
description: Install tools

inputs:
  is-builder:
    description: 'Installs required build tools and updates cache'
    required: true
  rust:
    description: 'Rust toolchain'
    required: true

runs:
  using: "composite"

  steps:
    # Setup tool cache
    - name: Ensure .local/bin exists
      shell: bash
      run: |
        mkdir -p ~/.local/

    - name: Setup tool cache
      if: inputs.is-builder == 'true'
      uses: actions/cache@v3
      with:
        path: |
          ~/.local/
        key: ${{ runner.os }}-tools

    - name: Restore tool cache
      if: inputs.is-builder == 'false'
      uses: actions/cache/restore@v3
      with:
        path: |
          ~/.local/
        key: ${{ runner.os }}-tools

    # Add ~/.local/bin to PATH
    - name: Add ~/.local/bin to PATH
      shell: bash
      run: |
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        echo "$HOME/.local/bin" >> $env:Path

    # Install rust
    - name: Install rust ${{ inputs.rust }}
      uses: ./.github/actions/tools/rust
      with:
        rust: ${{ inputs.rust }}
        is-builder: ${{ inputs.is-builder }}

    # Install protoc
    - name: Install protoc
      if: inputs.is-builder == 'true'
      uses: ./.github/actions/tools/protoc