name: tools
description: Install tools

inputs:
  modify_cache:
    description: 'Installs required build tools and updates cache'
    required: true
  rust:
    description: 'Rust toolchain'
    required: true
  github_token:
    description: 'GitHub token'
    required: true

runs:
  using: "composite"

  steps:
    # Setup tool cache
    - name: Setup tool cache
      if: inputs.modify_cache == 'true'
      uses: ./.github/actions/util/cache
      with:
        path: |
          ~/.local/
        key: ${{ runner.os }}-tools
        modify_cache: ${{ inputs.modify_cache }}

    # Add ~/.local/bin to PATH
    - name: Add ~/.local/bin to PATH
      uses: ./.github/actions/util/add_to_path
      with:
        path: ~/.local/bin

    # Install rust
    - name: Install rust ${{ inputs.rust }}
      uses: ./.github/actions/tools/rust
      with:
        rust: ${{ inputs.rust }}
        modify_cache: ${{ inputs.modify_cache }}

    # Install protoc
    - name: Install protoc
      uses: ./.github/actions/tools/protoc
      with:
        github_token: ${{ inputs.github_token }}