name: screenshots
description: Install required build dependencies for the `screenshots` rust crate

runs:
  using: "composite"

  steps:
    - name: Install apt packages
      if: runner.os == 'Linux'
      uses: daaku/gh-action-apt-install@v4
      with:
        packages: libdbus-1-dev